### ISSUE TITLE
`timestamp::now_seconds()` is used in genesis module before setting timestamp 

### ISSUE THREAD

**Issue by vpanchal-supra** [Entropy-Foundation/aptos-core#38]
`create_vesting_without_staking_pools` method of `genesis` module uses `timestamp::now_seconds()` to get current timestamp before setting timestamp using `update_global_time`, Hence `now_seconds` will always return `0` as timestamp.
- And the issue due to this is happening in vesting contract, `start_timestamp_secs` attribute is getting initialized as `cliff_period_value + 0` instead of `cliff_period_value + cur_timestamp`

**Comment by sjoshisupra** [comment]
Fixed in #44 .
Now the Rust layer is supposed to provide appropriate initialization parameters
(1) Provide `genesis_timestamp` as `0` and provide very large cliff periods for vesting/delegation pools
(2) Provide recent wall clock time as `genesis_timestamp`, even if the actual network starts within a few days, it doesn't matter since vesting/delegation are in the scale of months/years.
